version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: alimenta-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: alimenta
      POSTGRES_PASSWORD: alimenta123
      POSTGRES_DB: alimenta_plus
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
